//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMiniProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }
        [Required]
        public string StudentName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        [Required]
        public string PhoneNo { get; set; }
        public string Email { get; set; }
    }
}
